# Generated by Django 4.2 on 2023-05-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monhoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.FloatField(max_length=10)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('dcc', models.IntegerField()),
                ('dthi', models.IntegerField()),
                ('dtb', models.IntegerField()),
                ('t4', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
            ],
        ),
    ]
